#!/bin/bash

###############################################################################
#
# neovim
#
# Do not execute this script directly. It should only be executed from within
# dfsetup.
#
# If you want to only install neovim, then execute 'dfsetup neovim'.
#
###############################################################################

set -e

source ./util/brew.sh
source ./util/dirname.sh
source ./util/print.sh

function deps() {
  pip2 install --upgrade neovim
  pip3 install --upgrade neovim
}

function install() {
  brew_install neovim
}

function main() {
  deps && install
}

main "$@"
