#!/bin/bash

###############################################################################
#
# langs/javascript
#
# Do not execute this script directly. It should only be executed from within
# dfsetup.
#
# If you want to only install langs/javascript, then execute 'dfsetup langs/javascript'.
#
###############################################################################

set -e

source ./util/print.sh
source ./util/dirname.sh

function install() {
  print_info 'Installing langs/javascript...'
  brew install node
  brew install npm
  brew install yarn
  brew install nvm
  echo ''
  print_info 'Finished installing langs/javascript!'
  echo ''
}

function main() {
  install
}

main "$@"
