#!/bin/bash

###############################################################################
#
# langs/javascript
#
# Do not execute this script directly. It should only be executed from within
# dfsetup.
#
# If you want to only install langs/javascript, then execute 'dfsetup langs/javascript'.
#
###############################################################################

set -e

source ./util/dirname.sh
source ./util/brew.sh
source ./util/print.sh

function install() {
  print_info 'Installing langs/javascript...'
  brew_install node
  brew_install npm
  brew_install yarn
  brew_install nvm
  print_info 'Finished installing langs/javascript!'
  echo ''
}

function main() {
  install
}

main "$@"
