#!/usr/bin/env expect -f

set timeout 5
match_max 100000

expect_before {
  timeout { puts "timeout"; exit 2 }
  eof     { puts "eof";     exit 1 }
}

set user $env(USER)
set cwd [exec bash -c dirs +0]
set hostname [exec hostname]
set branch [exec git branch]

spawn bash
expect -exact "\[?2004h\[0;32m\[✔\]\[0m \[0;33m$user\[0m@\[0;32m$hostname\[0m:\[0;34m$cwd\[0m \[0;35m($branch)\[0m \$ "

send -- ""
expect eof
