#!/bin/bash

###############################################################################
#
# langs/python
#
# Do not execute this script directly. It should only be executed from within
# dfsetup.
#
# If you want to only install langs/python, then execute 'dfsetup langs/python'.
#
###############################################################################

set -e

source ./util/print.sh
source ./util/dirname.sh

function install() {
  print_info 'Installing langs/python...'
  brew install python
  brew install python3
  brew install pip2
  brew install pip3
  echo ''
  print_info 'Finished installing langs/python!'
  echo ''
}

function main() {
  install
}

main "$@"
