#!/bin/bash

###############################################################################
#
# langs/python
#
# Do not execute this script directly. It should only be executed from within
# dfsetup.
#
# If you want to only install langs/python, then execute 'dfsetup langs/python'.
#
###############################################################################

set -e

source ./util/dirname.sh
source ./util/brew.sh
source ./util/print.sh

function install() {
  print_info 'Installing langs/python...'
  brew_install python
  brew_install python3
  brew_install pip2
  brew_install pip3
  print_info 'Finished installing langs/python!'
  echo ''
}

function main() {
  install
}

main "$@"
