#!/bin/bash

###############################################################################
#
# langs/golang
#
# Do not execute this script directly. It should only be executed from within
# dfsetup.
#
# If you want to only install langs/golang, then execute 'dfsetup langs/golang'.
#
###############################################################################

set -e

source ./util/brew.sh
source ./util/dirname.sh
source ./util/print.sh

function install() {
  brew_install go
}

function main() {
  install
}

main "$@"
