#!/bin/bash

###############################################################################
#
# langs/golang
#
# Do not execute this script directly. It should only be executed from within
# dfsetup.
#
# If you want to only install langs/golang, then execute 'dfsetup langs/golang'.
#
###############################################################################

set -e

source ./util/brew.sh
source ./util/dirname.sh
source ./util/print.sh

function install() {
  print_info 'Installing langs/golang...'
  brew_install go
  print_info 'Finished installing langs/golang!'
  echo ''
}

function main() {
  install
}

main "$@"
